@echo off
echo Creating venv...
python -m venv venv

echo Activating venv...
call venv\Scripts\activate

echo Installing dependencies...
pip install -r requirements.txt

echo Starting Streamlit app...
streamlit run app.py